### ISSUE TITLE
正常响应文件但文件损坏

### ISSUE THREAD

**Issue by AFatMan** [jasonkung22/gateway-api-encrypt#1]
感谢分享源码

***问题描述***
引入使用后, 发现当接口用于导出文件时会导致文件损坏

***个人解决办法***
经验证, 发现主要原因是 `ResponseEncryptFilter` 中 `RewriteFunction<String, String>` 使用的是 `String` 导致

1. 我这边修改为 `RewriteFunction<byte[], byte[]>` 并修改对应逻辑后, 文件能正常导出并打开。

2. 当然也可以给响应加密加上白名单跳过重写响应这一步

***其他补充***
另外还发现一个小问题, 例如
`cn.futuai.open.encrypt.filter.request.RequestApiDecryptFilter#decryptRequestParam` 中 `ApiEncryptUtil.aesDecrypt` 产生的异常在`ApiEncryptUtil` 里面已经捕获了, 导致`decryptRequestParam` 方法无法抛出`ApiDecryptException`  异常

**Comment by jasonkung22** [comment]
感谢提出问题，导出文件的场景我确实没有还测试过，实际应用场景可能黑名单模式用得毕竟多，所以没有发现反馈的问题。我最近修复一下反馈的两个问题
